services:
  server:
    build:
      context: .
      target: server
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ROOT_URI=http://localhost:8000
      - COOKIE_SECRET_KEY=pXSSCKA8bbH5maDK0IhkeZv4qcCg95JLn/xHzBXE5hg=
      - DATA_PATH=/data
      - JOBS=50
      - BATCH_SIZE=50
      - POSTGRES_URI=postgres://scraper:scraper@postgres:5432/scraper
    ports:
      - 8000:8000
    volumes:
      - ./data/scraped:/data
      - ./.cache:/root/.cache/gbif-scraper
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=scraper
      - POSTGRES_DB=scraper
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper"]
      interval: 5s
      timeout: 5s
      retries: 5
