ALTER TABLE "medias" ADD "manual_x" DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE "medias" ADD "manual_y" DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE "medias" ADD "manual_width" DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE "medias" ADD "manual_height" DOUBLE PRECISION DEFAULT NULL;
